version: '3'
services: 
  node-app:
    build:
      context: .   # where you build ? . mean from dckerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=Production
    env_file:
      - ./.env
    command: npm start